namespace MineSharp.Core.Protocol.PacketTypes;

/// <summary>
/// Chat Message packet structure (0x08 serverbound).
/// Sent by client when player types a chat message.
/// </summary>
public class ChatMessagePacket
{
    /// <summary>
    /// The chat message content (max 256 characters).
    /// </summary>
    public string Message { get; set; } = string.Empty;

    /// <summary>
    /// Timestamp in milliseconds since epoch (1 Jan 1970, midnight, UTC).
    /// </summary>
    public long Timestamp { get; set; }

    /// <summary>
    /// The salt used to verify the signature hash. Randomly generated by the client.
    /// </summary>
    public long Salt { get; set; }

    // Note: The following fields are part of the protocol but not needed for basic chat functionality:
    // - Signature (Optional Byte Array, 256 bytes) - RSA signature for message authentication
    // - Message Count (VarInt) - Number of signed clientbound chat messages seen
    // - Acknowledged (Fixed BitSet, 20 bits) - Bitmask of acknowledged messages
    // - Checksum (Byte) - Validation checksum
    // These can be added later if signature validation is needed.
}

